fluent/syntax/ast.py, tests/syntax/test_ast_json.py, tools/parse.py
Working with ASTs serialized to JSON requires a way to build AST objects from
JSON objects.  fluent.syntax.ast.from_json takes a JSON representation of an
AST as input and returns AST nodes.
ast.Node.toJSON is also now called to_json to adhere to PEP8.
=> Introduce fluent.syntax.ast.from_json

fluent/migrate/context.py, fluent/migrate/transforms.py, fluent/migrate/util.py, fluent/syntax/ast.py, fluent/syntax/parser.py, fluent/util.py, tests/syntax/fixtures_structure/message_with_empty_pattern.json, tests/syntax/fixtures_structure/placeable_at_eol.json, tests/syntax/fixtures_structure/resource_comment.json, tests/syntax/fixtures_structure/resource_comment_trailing_line.json, tests/syntax/fixtures_structure/section.json, tests/syntax/fixtures_structure/simple_message.json, tests/syntax/fixtures_structure/standalone_comment.json, tests/syntax/test_ast_json.py, tests/syntax/test_behavior.py, tests/syntax/test_entry.py, tests/syntax/test_structure.py
Most AST nodes can now have a Span. Use `FluentParser(with_spans=True)` to enable this behavior.  The `with_annotations` config option to `FluentParser` has been removed. The parser always produces Annotations if necessary now.
=> Add Spans to all Nodes

fluent/migrate/transforms.py, fluent/syntax/ast.py, fluent/syntax/ftlstream.py, fluent/syntax/parser.py, fluent/syntax/serializer.py, tests/syntax/fixtures_behavior/indent.ftl, tests/syntax/fixtures_behavior/multiline_with_non_empty_first_line.ftl, tests/syntax/fixtures_behavior/multiline_with_placeables.ftl, tests/syntax/fixtures_behavior/placeable_in_placeable.ftl, tests/syntax/fixtures_behavior/section_with_nl_in_the_middle.ftl, tests/syntax/fixtures_structure/placeable_at_eol.ftl, tests/syntax/fixtures_structure/placeable_at_eol.json
WIP. Implement https://github.com/projectfluent/fluent/pull/52.
This doesn't pass structure tests because the AST changes, obviously. All but one behavior tests pass. I'm trying to find the bug.
=> Add the Placeable node

.travis.yml, tests/migrate/test_concat.py, tests/migrate/test_literal.py, tests/migrate/test_merge.py, tests/migrate/test_plural.py, tests/migrate/test_replace.py, tox.ini
Add testing for python 2.7 with compare-locales and without. As compare-locales doesn't support py3, we don't do that for 3.6 yet.
The test failures were just in the actual test code, so this fix is low-impact.
=> Compare locales bug 1382622

.travis.yml, setup.py, tests/syntax/test_behavior.py, tests/syntax/test_structure.py, tox.ini
=> Run Structure and Behavior tests in Python 3

tools/migrate/blame.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1411943
Mercurial 4.3 changed the format of the "annotate" command. See
https://www.mercurial-scm.org/wiki/Release4.3
=> Bug 1411943 - Fix Blame for Mercurial 4.3+

fluent/migrate/__init__.py, fluent/migrate/context.py, fluent/migrate/errors.py, fluent/migrate/merge.py, fluent/migrate/transforms.py, tests/migrate/fixtures/en-US/privacy.ftl, tests/migrate/fixtures/pl/privacy.dtd, tests/migrate/fixtures/pl/privacy.ftl, tests/migrate/test_concat.py, tests/migrate/test_context.py, tests/migrate/test_context_real_examples.py, tests/migrate/test_copy.py, tests/migrate/test_merge.py, tests/migrate/test_plural.py, tests/migrate/test_replace.py, tests/migrate/test_source.py, tools/migrate/examples/about_dialog.py, tools/migrate/examples/about_downloads.py, tools/migrate/examples/bug_1291693.py, tools/migrate/migrate-l10n.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1321279
=>  Bug 1321279 - Read target FTL files before migrations.

fluent/migrate/context.py, tests/migrate/fixtures/en-US/existing.ftl, tests/migrate/fixtures/pl/existing.dtd, tests/migrate/fixtures/pl/existing.ftl, tests/migrate/test_context.py, tools/migrate/README.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1318960
=> Bug 1318960 - Migrate files only when their messages change

fluent/migrate/transforms.py, tests/migrate/test_plural.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1366298
Languages with one plural category can have their translations migrated
directly to a single `Pattern` rather than a `SelectExpression` with one
variant. This will only happen when the number of variants in the
legacy translation is also one.
This also adds tests for languages with more categories than en-US.
=> Bug 1366298 - Skip SelectExpression in PLURALS for one plural category

fluent/migrate/transforms.py, tests/migrate/test_copy.py, tests/migrate/test_source.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1321290
=> Bug 1321290 - Migrate HTML entities to Unicode characters

fluent/migrate/context.py, tests/migrate/test_context.py, tests/migrate/test_context_real_examples.py, tools/migrate/examples/about_dialog.py, tools/migrate/examples/about_downloads.py, tools/migrate/examples/bug_1291693.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1420225
This is a simple change which makes it unnecessary to use `maybe_add_localization`—at all.
=> Bug 1420225 - Read legacy files when scanning for Sources in transforms

tools/migrate/blame.py, tools/migrate/migrate-l10n.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1428000
=> Bug 1428000 - Migrate: only annotate affected files

fluent/migrate/context.py, fluent/migrate/errors.py, tests/migrate/test_context.py, tools/migrate/blame.py, tools/migrate/migrate-l10n.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1435183
=> Bug 1435183 - Fix how files are passed to hg annotate

fluent/migrate/context.py, fluent/migrate/util.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1435181
=> Bug 1435181 - Warn about unknown FTL entities in transforms

fluent/migrate/transforms.py, fluent/syntax/ast.py, tests/migrate/test_concat.py, tests/migrate/test_replace.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1434998
=> Bug 1434998 - Allow for REPLACE values to be Patterns or PatternElements

fluent/syntax/ast.py
While working on https://bugzilla.mozilla.org/show_bug.cgi?id=1424682 I noticed that it's not possible to create a `CallExpression` without passing args, even if empty.
I think it'll be pretty common in migration code to want to call `FTL.CallExpression("PLATFORM")` etc.
=> Do not require args when creating a CallExpression

fluent/migrate/transforms.py, fluent/syntax/ast.py, tests/migrate/test_concat.py, tests/migrate/test_util.py
`CONCAT` used to override `FTL.BaseNode.traverse` and `FTL.BaseNode.to_json` because of its use of the `*elements` varargs in `__init__`.
Overriding `to_json` isn't required because the base mathod already supports lists.
<del>For traverse, I refactored the code slightly to only really override what's absolutely required to reconstruct an instance of CONCAT in traverse. The new BaseNode.get_init_args method returns a tuple of (args, kwargs) which can be used to programmatically create a new instance of the same class.</del>
<ins>For traverse, we allow CONCAT to be constructed with both the *elements varargs (useful when writing migration specs) and with the elements=[…] keyword arg (used by traverse because elements is an attribute of CONCAT instances).</ins>
=> Allow CONCAT(*elements) and CONCAT(elements=[…])

fluent/migrate/context.py, tests/migrate/test_context.py, tests/migrate/test_context_real_examples.py, tests/migrate/test_merge.py
Partial translations may break the AST because they produce `TextElements` with `None` values. For now, explicitly skip any transforms which depend on at least one missing legacy string.
In the future we might be able to allow partial migrations in some situations, like migrating a subset of attributes of a message. See https://bugzilla.mozilla.org/show_bug.cgi?id=1321271.
=> Never migrate partial translations

fluent/migrate/__init__.py, tools/migrate/examples/about_dialog.py, tools/migrate/examples/about_downloads.py, tools/migrate/examples/bug_1291693.py, tools/migrate/migrate-l10n.py
When writing Fluent migration specs, only the transforms like `CONCAT`, `COPY`, `PLURALS` and `REPLACE` are really required. All other exports are either helpers or specific to tools/migrate/migrate-l10n.py.
Fixes #43.
=> Only expose the basic transforms from fluent.migrate

fluent/migrate/context.py, setup.py, tests/migrate/test_concat.py, tests/migrate/test_context.py, tests/migrate/test_context_real_examples.py, tests/migrate/test_copy.py, tests/migrate/test_merge.py, tests/migrate/test_plural.py, tests/migrate/test_replace.py, tests/migrate/test_source.py, tox.ini
Make compare-locales a hard requirement for running and testing fluent.migrate which already largely depends on it anyways. This reduces the complexity of imports as well as the burden of deciding if a TestCase depends on compare-locales or not. It also makes it less probable to accidentally skip migration tests with `python -m unittest discover`.
The following commands may be used to run tests:
- `python setup.py test` - Only syntax tests in tests/syntax will be run. compare-locales is not required.
- `python -m unittest discover` - All tests will be run. If compare-locales is missing, tests will error.
It's possible to run only syntax or only migrate tests by specifying the starting director on the CLI:
python -m unittest discover -s tests/syntax
python -m unittest discover -s …
=> Require compare-locales in fluent.migrate

fluent/syntax/ftlstream.py, tests/syntax/fixtures_structure/leading_dots.ftl, tests/syntax/fixtures_structure/leading_dots.json, tests/syntax/fixtures_structure/message_with_empty_pattern.ftl, tests/syntax/fixtures_structure/message_with_empty_pattern.json, tests/syntax/fixtures_structure/multiline-comment.ftl, tests/syntax/fixtures_structure/multiline-comment.json
`}`, `.`, `*` and `[` are only special when they appear at the beginning of indented Pattern lines. When a Pattern starts on the same line as `id =` or `[variant key]`, its first character doesn't carry any special meaning and it may be one of those four ones as well.
Port of https://github.com/projectfluent/fluent.js/pull/150.
=> Inline Patterns may start with any character

fluent/migrate/context.py, tests/migrate/test_context.py
When adding Terms, we didn't add them to the list of entries
to compare in MergeContext.messages_equal. When migrating
to fluent files where only Terms differ from changeset to changeset,
that lead to no migration being created for that changeset.
=> Compare Terms and Messages in migrations, fixes bug 1437833

fluent/syntax/ast.py, tests/syntax/test_equals.py
`BaseNode.equals` sorts order-agnostic fields such as attributes and variants in order to ensure the equality comparison works correctly even if the order of the elements differs. The code used to assume all variant keys were `VariantName` instances. We need to support numbers as keys as well.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1441799.
=> Bug 1441799 - Support number variant keys in BaseNode.equals

fluent/migrate/transforms.py, tests/migrate/test_concat.py, tests/migrate/test_context_real_examples.py, tests/migrate/test_copy.py, tests/migrate/test_plural.py, tests/migrate/test_replace.py, tests/migrate/test_source.py
Migrate empty translations as {""}. See https://bugzil.la/1441942.
<del>Empty plural variants are also kept as {""} to preserve as much of the original intent as possible. Dropping them could result in different behavior when the default variant is displayed instead.</del>
<del>This doesn't address migrating leading and trailing whitespace in non-whitespace-only legacy translations. See https://bugzil.la/1374246.</del>
<ins>See https://github.com/projectfluent/python-fluent/pull/54#issuecomment-371536006.</ins>
=> Migrate empty translations

fluent/util.py, tests/migrate/test_util.py
The replacements in a REPLACE transform are in a dict,
which fold() didn't go in to.
=> bug 1447905, missing dependencies in REPLACE

.gitignore, fluent/migrate/context.py, tests/migrate/test_context.py
This refactors `in_changeset` to its own method so that it can be tested explicitly.
Not refactoring all tests yet, but adding one example test on how to do that.
=> Refactor merge context bug 1436014

fluent/__init__.py
I tested this locally by installing the result in my tox envs of the compare-locales tests.
I tested this w/out 'fluent' in the setup.py packages, and that breaks, so I'm going for that in both fluent.syntax and fluent.migrate.
=> Make fluent.syntax a proper pkgutil-style namespace package, fixes bug 1452902

fluent.runtime/tools/benchmarks/README.md, fluent.runtime/tools/benchmarks/fluent_benchmark.py, fluent.runtime/tools/benchmarks/requirements.txt
I haven't figured out how to actually run this on travis.
I'd love if this would be extra jobs, maybe just on py2.7, py3.7, pypy2, pypy3?
Reminds me, we're not testing py3.7 at all yet, we need to. Which is partly #70.
=> Create benchmark for fluent.runtime (fixes #85)

fluent.runtime/fluent/runtime/types.py
=> types.py - compatibility for PyPy3 5.10 and later

fluent.runtime/fluent/runtime/__init__.py, fluent.runtime/fluent/runtime/resolver.py, fluent.runtime/fluent/runtime/utils.py, fluent.runtime/setup.py, fluent.runtime/tests/format/test_attributes.py, fluent.runtime/tests/format/test_parameterized_terms.py, fluent.runtime/tests/format/test_select_expression.py, fluent.runtime/tests/test_bundle.py, fluent.runtime/tox.ini
=> Update fluent.runtime for fluent.syntax 0.10

.travis.yml
This PR removes a now-unused Travis directive.
=> Travis: Remove unused sudo:false setting

fluent.syntax/fluent/syntax/ast.py, fluent.syntax/tests/syntax/fixtures_perf/workload-low.ftl, fluent.syntax/tests/syntax/test_visitor.py
This includes some performance tests to compare the visitor and a
traversal. Locally, the visitor is twice as fast.
This is the most basic Visitor pattern. I've had versions that were
more generic, and performance gains vanished quickly. In particular
optionally collecting results on exit halfed the performance benefits.
If we want to factor that in, we should have an independent base class
for that.
This should fix #68, I think.
=> Add a read-only visitor pattern.

fluent.syntax/fluent/syntax/ast.py, fluent.syntax/tests/syntax/test_equals.py, fluent.syntax/tests/syntax/test_visitor.py
=>  Add Transformer API for in-place manipulation of AST

fluent.syntax/fluent/syntax/ast.py, fluent.syntax/tests/syntax/test_visitor.py
I'm having second thoughts about the ast.Visitor.
I've tested https://phabricator.services.mozilla.com/D19137, and turns out that setting the state in the current visit is really hard. Mostly, because there's no natural per-Node pop.
Now, if I redo the visitor, it's closer to how Transformer works, and easier to do things like "I'm in NodeX" state. The code in c-l now becomes
```python
def visit_AttributeExpression(self, node):
self.attr = '.' + node.name.name
super(ReferenceCollector, self).generic_visit(node)
self.attr = ''
def visit_MessageReference(self, node):
self.refs[node.id.name + self.attr] = node
def visit_TermReference(self, node):
if not self.attr:
self.refs['-' + node.id.name] = node
```
The code in D19137 actually fails tests if the `AttributeReference.ref` isn't the first …
=> Redo read-only visitor

fluent.runtime/fluent/runtime/__init__.py, fluent.runtime/fluent/runtime/prepare.py, fluent.runtime/fluent/runtime/resolver.py, fluent.runtime/fluent/runtime/types.py, fluent.runtime/fluent/runtime/utils.py, fluent.runtime/setup.py, fluent.runtime/tests/test_bomb.py, fluent.runtime/tox.ini
This is my all-test-passing state of the proposal I made in https://discourse.mozilla.org/t/python-fluent-runtime-plans/35290/10.
I've given this a try to see how this is doing before we do changes to the non-compiling API that don't perform, notably I'm looking at #92.
This isn't yet in a state where it can be reviewed, sadly, because I didn't get to remove unused code yet. I wouldn't be surprised if this could end up being the same amount of code in the end as the current dispatch resolver.
The good news is that in the template benchmark, I cut down mean and median to 50% of what they're on master right now.
=> Refactor resolver into a tree of callable objects, or partially evaluated

fluent.syntax/fluent/syntax/ast.py, fluent.syntax/tests/syntax/test_equals.py
This goes back to the conversation in https://github.com/projectfluent/fluent.js/pull/172
=> .equals should not ignore Variant and Attribute order, fixes #111

fluent.runtime/fluent/runtime/__init__.py, fluent.runtime/fluent/runtime/prepare.py, fluent.runtime/fluent/runtime/resolver.py, fluent.runtime/tests/format/test_placeables.py
This patch removes state from the compiled tree.
For one, the recursion detection on patterns keeps its state in
the `ResolverEnvironment` now, instead of in the compiled tree.
Also, the question of bidi isolation is now kept in the resolver
context, instead of in the compiled tree.
For single placeables, which don't get bidi-isolated ever, there's
now a distinct NeverIsolatingPlaceable, which also takes care of
resolving fluent values to strings.
This should fix the test cases in #108 and #109
Luke, picking this up again, does this look good?
FWIW, I call this "threadsafer" as I think there might still be race conditions inside `FluentBundle.lookup`. I'm not sure they're bad, though. I think the worst case is that we compile a message twice, and then use the message value and attributes …
=> Make resolver threadsaf(er) again, fix isolation

.travis.yml, fluent.runtime/setup.py, fluent.runtime/tox.ini, fluent.syntax/setup.py, fluent.syntax/tox.ini
We don't actually depend on anything that was added after 0.10, and a tight check gives problems with other tools (e.g. compare-locales is constrained to '>=0.10,<0.11').
=> fluent.runtime - broader dependency range for fluent.syntax

fluent.syntax/fluent/syntax/serializer.py, fluent.syntax/tests/syntax/test_serializer.py
`splitlines` returns `[]` for empty strings, which is not what we
want, use `split` instead.
This matches what `@fluent.syntax` does on the js side.
Zibi, can you do a review on this one?
=> Use `split` instead of `splitlines` to serialize comments (fixes #119)

fluent.syntax/fluent/syntax/parser.py, fluent.syntax/tests/syntax/fixtures_reference/call_expressions.ftl, fluent.syntax/tests/syntax/fixtures_reference/comments.ftl, fluent.syntax/tests/syntax/fixtures_reference/comments.json, fluent.syntax/tests/syntax/fixtures_reference/escaped_characters.ftl, fluent.syntax/tests/syntax/fixtures_reference/escaped_characters.json, fluent.syntax/tests/syntax/fixtures_reference/messages.ftl, fluent.syntax/tests/syntax/fixtures_reference/messages.json, fluent.syntax/tests/syntax/fixtures_reference/select_expressions.ftl, fluent.syntax/tests/syntax/fixtures_reference/select_expressions.json, fluent.syntax/tests/syntax/fixtures_reference/select_indent.ftl, fluent.syntax/tests/syntax/fixtures_reference/select_indent.json, fluent.syntax/tests/syntax/fixtures_reference/term_parameters.ftl, fluent.syntax/tests/syntax/fixtures_reference/terms.ftl, fluent.syntax/tests/syntax/fixtures_reference/terms.json, fluent.syntax/tests/syntax/fixtures_reference/zero_length.json
This is picking up the tests for projectfluent/fluent#281,
and adjusts the parser to pass those tests.
This is the port of https://github.com/projectfluent/fluent.js/pull/422.
=> Allow whitespace before CallArguments (fixes #124)

fluent.runtime/CHANGELOG.rst, fluent.runtime/docs/conf.py, fluent.runtime/docs/index.rst, fluent.runtime/docs/internals.rst, fluent.runtime/docs/requirements.txt, fluent.runtime/docs/usage.rst, fluent.runtime/fluent/runtime/__init__.py, fluent.runtime/fluent/runtime/fallback.py, fluent.runtime/fluent/runtime/resolver.py, fluent.runtime/fluent/runtime/utils.py, fluent.runtime/setup.py, fluent.runtime/tests/format/test_arguments.py, fluent.runtime/tests/format/test_attributes.py, fluent.runtime/tests/format/test_builtins.py, fluent.runtime/tests/format/test_functions.py, fluent.runtime/tests/format/test_isolating.py, fluent.runtime/tests/format/test_parameterized_terms.py, fluent.runtime/tests/format/test_placeables.py, fluent.runtime/tests/format/test_primitives.py, fluent.runtime/tests/format/test_select_expression.py, fluent.runtime/tests/test_bomb.py, fluent.runtime/tests/test_bundle.py, fluent.runtime/tests/test_fallback.py, fluent.runtime/tools/benchmarks/fluent_benchmark.py, fluent.runtime/tox.ini
This was an experimental branch to demonstrate how to implement the bundle API of other implementations, and to create a base Localization class for developers to use, and for binding-implementers to customize.
Per https://discourse.mozilla.org/t/experimental-release-of-python-fluent-runtime/47569/2, we should go ahead and merge this now.
CC @stasm @spookylukey
=> Bundle API and Localization class

.github/workflows/lint.yml, .github/workflows/syntax-tests.yml, fluent.runtime/runtests.py, fluent.syntax/setup.py, fluent.syntax/tests/syntax/test_ast_json.py, fluent.syntax/tests/syntax/test_entry.py, fluent.syntax/tests/syntax/test_equals.py, fluent.syntax/tests/syntax/test_reference.py, fluent.syntax/tests/syntax/test_serializer.py, fluent.syntax/tests/syntax/test_stream.py, fluent.syntax/tests/syntax/test_structure.py, fluent.syntax/tests/syntax/test_visitor.py
Making the test runner actually use the python you run it with.
Then, add gh-actions test automation.
As I saw a deprecation warning on master, I went in and fixed
the tests, including flake8.
And thus I switched on flake8 for all of fluent.syntax.
=> fluent.syntax tests and linting on gh actions

.github/workflows/fluent.runtime.yml, .github/workflows/lint.yml
Lesson learned, workflow bades go by workflow name.
Using one workflow for the runtime package.
Test the latest compat version of syntax against master, as
well as master syntax against master runtime. The latter is
OK to fail.
Move linter from lint workflow to runtime workflow.
=> Automate fluent.runtime on gh actions

.github/workflows/fluent.integration.yml, .github/workflows/fluent.runtime.yml, .github/workflows/fluent.syntax.yml
This factors the integration jobs back into its own workflow.
This is to allow for the pygments module to also have integration
tests, and we're ignoring them for status (and thus badges)
anyway.
=> Make gh actions only run when needed.

.github/workflows/documentation.yml, docs/Makefile, docs/_static/project-fluent.css, docs/_templates/layout.html, docs/conf.py, docs/index.rst, fluent.runtime/docs/index.rst, fluent.runtime/setup.cfg, fluent.runtime/setup.py, fluent.syntax/setup.cfg, fluent.syntax/setup.py, scripts/build-docs
This builds and hosts, if you use the following mammoth to rsync to a repo with gh-pages:
```
rsync -rav --include='**/_static/documentation_options.js' --exclude='fluent.*/**/_static/*' --exclude='.*' _build/python-fluent/ ....
```
The docs are generated via a script, `./scripts/build-docs python-fluent`.
=> Build top-level, syntax, and runtime documentation from one config

fluent.syntax/fluent/syntax/serializer.py, fluent.syntax/tests/syntax/fixtures_reference/special_chars.ftl, fluent.syntax/tests/syntax/fixtures_reference/special_chars.json, fluent.syntax/tests/syntax/test_serializer.py
Port of https://github.com/projectfluent/fluent.js/pull/513.
=> (fluent.syntax) Don't drop to newline when serializing patterns starting with special chars

fluent.syntax/fluent/syntax/parser.py, fluent.syntax/tests/syntax/fixtures_reference/tab.ftl, fluent.syntax/tests/syntax/fixtures_reference/tab.json
Fixes #173 
Tabs were defined to be text, not whitespace, in projectfluent/fluent#167, but this change was not reflected in the trailing whitespace trimming.
=> Treat tab as text, not whitespace

.github/workflows/documentation.yml, .github/workflows/fluent.integration.yml, .github/workflows/fluent.runtime.yml, .github/workflows/fluent.syntax.yml, fluent.docs/README.rst
These changes should go together with the actual rename of the default branch, which should be pretty painless.
=> Rename default branch as main

.github/workflows/fluent.runtime.yml, .github/workflows/fluent.syntax.yml, fluent.docs/setup.py, fluent.runtime/fluent/runtime/__init__.py, fluent.runtime/fluent/runtime/builtins.py, fluent.runtime/fluent/runtime/bundle.py, fluent.runtime/fluent/runtime/errors.py, fluent.runtime/fluent/runtime/fallback.py, fluent.runtime/fluent/runtime/prepare.py, fluent.runtime/fluent/runtime/resolver.py, fluent.runtime/fluent/runtime/types.py, fluent.runtime/fluent/runtime/utils.py, fluent.runtime/setup.cfg, fluent.runtime/setup.py, fluent.runtime/tests/test_types.py, fluent.runtime/tox.ini, fluent.syntax/fluent/syntax/__init__.py, fluent.syntax/fluent/syntax/ast.py, fluent.syntax/fluent/syntax/errors.py, fluent.syntax/fluent/syntax/parser.py, fluent.syntax/fluent/syntax/serializer.py, fluent.syntax/fluent/syntax/stream.py, fluent.syntax/fluent/syntax/visitor.py, fluent.syntax/setup.cfg, fluent.syntax/setup.py, fluent.syntax/tox.ini
Fixes #165 
The work here is split into commits that may be easier to review separately. The internal hints for the runtime resolver and compiler are pretty weak, as the base implementation is making explicit use of the language being fundamentally untyped.
The bugs that are fixed are all various sorts of corner cases that the code didn't account for previously; the errors tend to follow similar cases in fluent.js.
While adding the types I used both mypy and pylance; the added CI tests only apply `mypy --strict` as the strict-mode pylance checks don't all pass (mostly due to using `Unknown` values in places that accept `Any`).
=> Add type hints to fluent.syntax & fluent.runtime

fluent.runtime/setup.py
#163 dropped support of Python < 3.6, but haven't set minimal Python version in setup.py. Currently only classifiers are set, which are just additional information used for search, these values are not checked during package installation.
Adding `python_requires` to `setup.py` to allow package managers to check that package is compatible only with Python >= 3.6.
fix #188
=> Prevent package from installing on Python < 3.6

fluent.runtime/fluent/runtime/bundle.py, fluent.runtime/fluent/runtime/resolver.py, fluent.runtime/fluent/runtime/types.py, fluent.runtime/tests/format/test_primitives.py, fluent.runtime/tests/format/test_select_expression.py, fluent.runtime/tests/test_bundle.py
The type option is simply ignored outside of a select expression, and allows to select based on CLDR plural categories for ordinals (which differ from normal plurals aka cardinal numbers).
This is as per (part* of) the docs, and per javascript implementation, see projectfluent/fluent#259 -- I haven’t found any definition of NUMBER() in the actual spec. Fixes #192.
\*  [Here yes](https://projectfluent.org/fluent/guide/selectors.html) but [not here](https://projectfluent.org/fluent/guide/functions.html#number).
=> Support type parameter (ordinal/cardinal) in NUMBER() select expressions

fluent.runtime/tests/test_types.py
As part of the Babel 2.15.0 release, an upgrade to CLDR 44 was included. The new CLDR version changes the date format for the en-GB locale to remove a comma in the full format.
This change updates the tests so that both the old and new formats can be handled. This is done instead of pinning babel to a lower version, since we just care that formatting takes place.
[Babel issue]: https://github.com/python-babel/babel/issues/1070
[CLDR 44 changes]: https://www.unicode.org/cldr/charts/44/delta/en.html#Formats%20-%20Standard%20-%20Date%20Formats
=> Update tests to support Babel 2.15.0

fluent.syntax/fluent/syntax/parser.py, fluent.syntax/tests/syntax/test_entry.py, fluent.syntax/tests/syntax/test_structure.py
This PR contains a small change to stop adding span information to `Annotation` elements when `with_spans` is set to `False` for the parser.
I've pulled this into its own PR because it wasn't obvious whether this behaviour was intentional or not (I could see an argument that annotations are a bit useless without span information). If this isn't needed, I'm happy to close this PR.
Note that the broken tests are unrelated to this PR, and are fixed in https://github.com/projectfluent/python-fluent/pull/203.
=> Respect the `with_spans` parser option for annotations

.github/workflows/ci.yml, fluent.runtime/tests/__init__.py, fluent.runtime/tests/test_fallback.py, fluent.runtime/tests/test_utils.py, fluent.runtime/tests/utils.py
`test_fallback.py` uses simple string compare (through dict) to simulate files. On Windows, paths are formed with `\` instead of `/`, which causes inconsistency in the string compare, producing the failures below. (Specifically, the `\`s were created by `os.path.join` in `FluentResourceLoader`.)
Without this fix, running `python -m unittest discover -s fluent.runtime` on Windows on df5ef402be3cf61f4a16e54e490e37e9cf276c05 produced the following failures: (Some folders in paths omitted)
```
....................................................................................................................................................E.F.F.D:\***\python-fluent\fluent.runtime\fluent\runtime\types.py:361: UserWarning: FluentDateType option hour12 is not yet supported …
```
=> Fix test failures on windows
